### ISSUE TITLE
error with police job evidence 

### ISSUE THREAD

**Issue by zyloxfps** [LeSiiN/lsn-evidence#1]
when i use the flash light nothing shows up
![image](https://github.com/LeSiiN/lsn-evidence/assets/148844818/4798c5c9-3de2-4f95-a4c9-79d7e0c00d34)

**Comment by LeSiiN** [comment]
Did u do all the steps?

**Comment by zyloxfps** [comment]
yeah i replaced my client and evidence and added the items and removed the ammo stuff from police job

**Comment by zyloxfps** [comment]
i cleared cache and restarted server and still same error 
![image](https://github.com/LeSiiN/lsn-evidence/assets/148844818/c8a8a093-9d47-4ffd-b349-4f181260772e)

**Comment by LeSiiN** [comment]
What client and evidence, evidence.lua is client, the main.lua is server side

**Comment by zyloxfps** [comment]
client

**Comment by LeSiiN** [comment]
> client

cant really do anything with this message

**Comment by zyloxfps** [comment]
i put both in client

**Comment by LeSiiN** [comment]
> i put both in client

Sry that was incorrectly in the readme.
the main.lua should replace the server side of policejob
The evidence.lua should replace the client side of policejob

**Comment by zyloxfps** [comment]
oh okay ill fix it

**Comment by LeSiiN** [comment]
Okay, please let me know if that worked. If so i will close this issue

**Comment by zyloxfps** [comment]
i have no errors now but still no markers 
![image](https://github.com/LeSiiN/lsn-evidence/assets/148844818/b49c2022-6df3-4655-ae89-99f906cce8ed)

**Comment by LeSiiN** [comment]
are u police officer / and on duty

**Comment by LeSiiN** [comment]
Lets swtich to #live-support in the PS Discord

**Comment by LeSiiN** [comment]
got it fixed?

**Comment by zyloxfps** [comment]
yes

**Comment by LeSiiN** [comment]
What was wrong? I wanna know for future bug report
