### ISSUE TITLE
I use mz-storerobbery error

### ISSUE THREAD

**Issue by neil0921111** [LeSiiN/lsn-evidence#11]
![image](https://github.com/LeSiiN/lsn-evidence/assets/147937483/197a996b-aced-4397-915f-c8da20a2ffe2)
This error occurred when I finished robbing a supermarket

**Comment by LeSiiN** [comment]
show me the part where storerobbery sends evidence

**Comment by neil0921111** [comment]
join your discord  ok ?

**Comment by neil0921111** [comment]
https://github.com/MrZainRP/mz-storerobbery

**Comment by LeSiiN** [comment]
okay join PS discord and join this channel, https://discordapp.com/channels/897744257237000222/1190806357515964446
