### ISSUE TITLE
Script Error when picking up Footprint evidence when Config.PoliceJob = "hi-dev"

### ISSUE THREAD

**Issue by ThatMadCap** [LeSiiN/lsn-evidence#16]
Environment:
hi-dev qb-policejob: 1.4.1
lsn-evidence: '0.0.8'

Expected results:
This is the functionality tested using Config.PoliceJob = "qb"
Player runs, leaves footprint. Footprint sprite is drawn and shown when using flashlight. Interact with "E" sprite and pickup item.

Steps to reproduce error:
1. Set Config.PoliceJob = "hi-dev"
2. Player runs, leaves footprint. Footprint sprite is drawn and shown when using flashlight. Interact with "E" sprite and pickup item.
3. Script Error: ![image](https://github.com/LeSiiN/lsn-evidence/assets/95227673/9023d0ad-10d2-4459-aadc-1bf0f6443639)

**Comment by LeSiiN** [comment]
https://i.imgur.com/UEQoiYU.png
this should fix it

**Comment by ThatMadCap** [comment]
Changing it to "Footprints" does fix this.
