### ISSUE TITLE
hi-dev policejob lab

### ISSUE THREAD

**Issue by BubbleDudeAT** [LeSiiN/lsn-evidence#18]
Is this working with Hi-Dev Policejob Lab? Because i cant see any bullets in my menu

**Comment by LeSiiN** [comment]
i made some updates
pls download

https://github.com/LeSiiN/lsn-evidence/releases/tag/0.1.3
make sure to follow the readme and REPLACE the files

**Comment by BubbleDudeAT** [comment]
Still nothing showing up added everything in the readme, do i need to put it in the evidence stash? or do i keep it in the inventory?

**Comment by LeSiiN** [comment]
Could u join the PS Discord and type in the Evidence Script release chat?

**Comment by LeSiiN** [comment]
Keeping this Opened ( close if fixed )

**Comment by merpindia** [comment]
same issue

**Comment by RazerGhost** [comment]
This issue should hopefully be fixed now
