### ISSUE TITLE
Evidence Not showing up at all

### ISSUE THREAD

**Issue by mistressUwU** [LeSiiN/lsn-evidence#19]
Hi, using Hi-dev policejob, shot a couple rounds at the wall, no markers or lines showed up to collect. It was working before the update, I think it was 0,0.8 and I havent changed anything other than updating to 0.1.3

Installed Version 0.1.3

Tried: 
1) Fresh install of Hi-dev policejob, replaced main and evidence lua 
2) Fresh install of evidence script, checked config and made sure everything is done there as well
3) Replace js.app in qb-inventory with NEW version 

Also tried, reverting back to 0.0.8 and nothing shows up either @.@

No errors in client or server side

**Comment by mistressUwU** [comment]
Also tried, to go back to 0.0.8 and nothing shows up either @.@

**Comment by LeSiiN** [comment]
my guess is, u got the flashlight in ur hands the whole time, which does not work that way, no errors means that everything is working as it should

**Comment by mistressUwU** [comment]
So what you meant was, if I shine the flashlight once the evidence will show up?

**Comment by LeSiiN** [comment]
After each script restart the script checks your hands, but it only does it when using the weapon, so after each restart, use the flashlight twice to pack it, and pull it back out, then when aiming the loop starts so the markers show

**Comment by mistressUwU** [comment]
Ahh okay. Thank you for explaining it to me. I will try that.

**Comment by LeSiiN** [comment]
Still got question, join the Project Sloth Discord and ask in the support channel <3
