### ISSUE TITLE
Hello laserpointer withdrawn

### ISSUE THREAD

**Issue by rodrigofueda** [LeSiiN/lsn-evidence#21]
I would like to know if there is any way to show the evidence in the ps-camera photos since the laserpointer was removed and it no longer shows without pointing the flashlight

**Comment by LeSiiN** [comment]
Oh, while changing the versions and making it better i might removed it. When i got time i will add it again.

**Comment by rodrigofueda** [comment]
Ah yes, I wish I could take photos with the PS camera and the evidence would appear, but that's ok.

**Comment by LeSiiN** [comment]
https://github.com/LeSiiN/lsn-evidence/commit/624503d206975806404de9ff43d64f457f882ba6 fixed
