### ISSUE TITLE
Hello, I tried to take a photo to show the evidence and nothing, could you help me?

### ISSUE THREAD

**Issue by rodrigofueda** [LeSiiN/lsn-evidence#22]
Hello, I tried to take a photo to show the evidence and nothing, could you help me?

**Comment by rodrigofueda** [comment]
![image](https://github.com/LeSiiN/lsn-evidence/assets/158107238/82d79a7e-e51d-481d-80aa-d37da72fe089)

**Comment by rodrigofueda** [comment]
![image](https://github.com/LeSiiN/lsn-evidence/assets/158107238/9dddd2b0-ab7f-43f9-ab8b-d933ccd94900)

the photo

**Comment by LeSiiN** [comment]
Did u update?

**Comment by rodrigofueda** [comment]
now it's working after this update ^^

**Comment by LeSiiN** [comment]
perfect <3
