### ISSUE TITLE
Console Error - @qb-policejob/client/evidence.lua:655: attempt to perform arithmetic on a nil value (field 'RemoveEvidence')

### ISSUE THREAD

**Issue by ChlxeThomson** [LeSiiN/lsn-evidence#7]
<img width="1249" alt="Screenshot 2024-01-24 235840" src="https://github.com/LeSiiN/lsn-evidence/assets/58238399/09ac7f24-09d6-479a-9b99-6f14eff404fe">
<img width="912" alt="Screenshot 2024-01-24 235845" src="https://github.com/LeSiiN/lsn-evidence/assets/58238399/724de657-57f3-499d-bea3-f21fc848fbaf">

My new QBCore Framework is less than 2 weeks old now*

After installing this script by following [This Video Tuturial](https://youtu.be/R2c80b8jVMA?si=Eqg3PjIAnFXQKNbY) i now get this error in my console

**Comment by LeSiiN** [comment]
U probably did something wrong, try again.
Only thing i could imagine is, u changed something in the config and fucked up

**Comment by ChlxeThomson** [comment]
I followed Kamaryn's video to a T, i didn't miss anything, only thing i changed was the Notify bit as i use **okokNotify**

<img width="528" alt="Screenshot 2024-01-27 142345" src="https://github.com/LeSiiN/lsn-evidence/assets/58238399/f9f4fd90-4e1a-4cb6-97b6-be5fb79c3ce0">

**Comment by LeSiiN** [comment]
> I followed Kamaryn's video to a T, i didn't miss anything, only thing i changed was the Notify bit as i use **okokNotify**
> 
> <img alt="Screenshot 2024-01-27 142345" width="528" src="https://private-user-images.githubusercontent.com/58238399/300184072-f9f4fd90-4e1a-4cb6-97b6-be5fb79c3ce0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNjU4OTgsIm5iZiI6MTcwNjM2NTU5OCwicGF0aCI6Ii81ODIzODM5OS8zMDAxODQwNzItZjlmNGZkOTAtNGUxYS00Y2I2LTk3YjYtYmU1ZmI3OWMzY2UwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDE0MjYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmOGU4ODRlZGFhNGQ2Y2MwMzVhODA0MGM2YjYzZDI4OWFhNGUyYTViMjU4MjZlNmE3NmQ1MDEzN2JiZTJjMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jVE0TLF959KQd8i3cLuK5Ax-KX-3Dg_6HawwW-WCW2I">

Pls read above, there is qb OR ox

**Comment by ChlxeThomson** [comment]
I changed it back to QB, now i get this

<img width="888" alt="Screenshot 2024-01-27 144349" src="https://github.com/LeSiiN/lsn-evidence/assets/58238399/ed393529-918b-42eb-947b-106d506e9d1e">

<img width="1068" alt="Screenshot 2024-01-27 144453" src="https://github.com/LeSiiN/lsn-evidence/assets/58238399/581d79de-a5e5-4384-b4e3-80bcf3ea11bc">

**Comment by LeSiiN** [comment]
Bro u should start reading ngl

**Comment by ChlxeThomson** [comment]
I am someone who has only just started to learn code, no need to be rude. I have no idea where i'm putting Trigger Server Events, i'm still learning so please dont be rude and maybe give me some guidance please

**Comment by LeSiiN** [comment]
> I am someone who has only just started to learn code, no need to be rude. I have no idea where i'm putting Trigger Server Events, i'm still learning so please dont be rude and maybe give me some guidance please

Okay, so pls add a — behind both triggerserverevents, change the notify to qb not QB or Qb and then it should work, for further help join the project sloth discord

**Comment by ChlxeThomson** [comment]
Thank you, i will try this and report back soon

**Comment by LeSiiN** [comment]
Close due to Player Issue.
Any further questions?
Join Project Sloth Discord
